name: Build Jupyter-Book documentation ğŸ“–

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - master
      - dev

# ----------------------------------------------------------------------------------------------------------------------

defaults:
  run:
    shell: bash
    working-directory: .

jobs:
  test-and-build:
    name: Build Jupyter-Book documentation
    runs-on: ubuntu-22.04

    steps:

      - name: Checkout ğŸ›
        uses: actions/checkout@v3

      - name: Install Setuptools dependencies ğŸ¼
        uses: py-actions/py-dependency-install@v4
        with:
          path: "requirements-setuptools.txt"

      # ----------------------------------------------------------------------------------------------------------------

      - name: Install PyCRAM dependencies ğŸ¼
        uses: py-actions/py-dependency-install@v4
        with:
          path: "requirements.txt"

      # ----------------------------------------------------------------------------------------------------------------
      - name: Install Jupyter-Book dependencies ğŸ“š
        uses: py-actions/py-dependency-install@v4
        with:
          path: "doc/requirements.txt"

      # ----------------------------------------------------------------------------------------------------------------
      - name: Build Jupyter-Book documentation ğŸ“
        working-directory: ./doc
        run: |
            jupyter-book build source